"""
Django settings for pos_backend project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-%#z20%dzsatq@pin7h##)(mudr*$fxdvuk2iyc&(wq+%#yak^3"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ENVIRONMENT = config('DJANGO_ENV', 'development')

# OpenAI API key – make sure to set OPENAI_API_KEY in your env/.env file or runtime environment
OPENAI_API_KEY = config('OPENAI_API_KEY', default='')

if ENVIRONMENT == 'production':
    DEBUG = False
    ALLOWED_HOSTS = [
        "localhost",
        "betab.ttincnc.com"
    ]
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:5173",
        "https://betab.ttincnc.com",
        "https://login.ttincnc.com",
        "https://beta.ttincnc.com"
    ]

    CSRF_TRUSTED_ORIGINS = [
        "http://localhost:5173",
        "https://betab.ttincnc.com",
        "https://login.ttincnc.com",
        "https://beta.ttincnc.com",
    ]
    CORS_ALLOW_ALL_ORIGINS = False
    
    # HTTPS Settings
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
else:
    DEBUG = True
    ALLOWED_HOSTS = ["*"]
    CORS_ALLOW_ALL_ORIGINS = True
    CSRF_TRUSTED_ORIGINS = [
        "http://localhost",
        "http://localhost:8000",
        "http://127.0.0.1",
        "http://127.0.0.1:8000",
        "http://localhost:3000",
        "http://localhost:5173",  # if used by React or other frontend
    ]

ENVIRONMENT = config('DJANGO_ENV', 'development')


# Application definition

INSTALLED_APPS = [
    "daphne",
    "channels",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "drf_spectacular",
    "corsheaders",
    "rest_framework",
    "custom_user",
    "commonapp",
    "chat",
    "assembly",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "pos_backend.middleware.AccessLogMiddleware",
    "custom_user.middleware.PayRatePermissionMiddleware",
]

ROOT_URLCONF = "pos_backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "pos_backend.wsgi.application"
ASGI_APPLICATION = "pos_backend.asgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

db_dir = BASE_DIR / "db"
db_dir.mkdir(parents=True, exist_ok=True)

# Use the same DB path for both local and Docker environments
DB_PATH = BASE_DIR / "db" / "db.sqlite3"

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": DB_PATH,
    }
}


# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.postgresql",
#         "NAME": config('DATABASE_NAME'),
#         "USER": config('DATABASE_USER'),
#         "PASSWORD": config('DATABASE_PASSWORD'),
#         "HOST": config('DATABASE_HOST'),
#         "PORT": "5432",
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "America/New_York"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [
    BASE_DIR / "static"
]


STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles/")

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


CORS_ALLOW_HEADERS = [
    "content-type",
    "accept",
    "x-csrftoken",
    "x-requested-with",
    "x-user-email",
    "Bearer",
    "Authorization",
    "content-disposition",
]


CORS_EXPOSE_HEADERS = [
    "content-disposition",
]

AUTH_USER_MODEL = "custom_user.Account"


MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PAGINATION_CLASS": "pos_backend.pagination.RelativeUrlPagination",
    "PAGE_SIZE": 10,
}


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=10),
    "REFRESH_TOKEN_LIFETIME": timedelta(hours=1),
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "AUTH_HEADER_TYPES": ("Bearer",),
}


# Email Configuration
# Static settings that don't change between providers
EMAIL_BACKEND = "commonapp.email_backend.DatabaseSMTPBackend"
EMAIL_USE_TLS = True

# Dynamic email settings will be loaded from database
# These are fallback values that will be overridden by database settings
EMAIL_HOST = "localhost"
EMAIL_PORT = 587
EMAIL_HOST_USER = ""
EMAIL_HOST_PASSWORD = ""
DEFAULT_FROM_EMAIL = ""

# Note: Email settings are dynamically loaded from PlatformConfig model
# You can override them with environment variables:
# EMAIL_HOST, EMAIL_PORT, EMAIL_HOST_USER, EMAIL_HOST_PASSWORD, DEFAULT_FROM_EMAIL


DATA_UPLOAD_MAX_NUMBER_FILES = 400
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760000
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000 

FRONTEND_BASE_URL = config("FRONTEND_BASE_URL", default="http://localhost:5173")
TWILIO_ACCOUNT_SID = config("TWILIO_ACCOUNT_SID", default="")
TWILIO_AUTH_TOKEN = config("TWILIO_AUTH_TOKEN", default="")


from celery.schedules import crontab
from kombu import Queue

CELERY_QUEUES = (
    Queue('default'),
    Queue('priority'),  # dedicated queue for email or priority tasks
)

REDIS_HOST = config("REDIS_HOST", "localhost")
REDIS_PORT = config("REDIS_PORT", "6379")

CELERY_BROKER_URL = f"redis://{REDIS_HOST}:{REDIS_PORT}/0"
CELERY_RESULT_BACKEND = f"redis://{REDIS_HOST}:{REDIS_PORT}/0"
print("CELERY_BROKER_URL:", CELERY_BROKER_URL)
print("CELERY_RESULT_BACKEND:", CELERY_RESULT_BACKEND)



CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"


CELERY_BEAT_SCHEDULE = {
    "close-drawer": {
        "task": "commonapp.tasks.close_expired_cash_drawers",
        "schedule": crontab(hour='*/4', minute=0),
    }
}


# Configure CHANNEL_LAYERS with fallback to in-memory if Redis is not available
import redis
REDIS_AVAILABLE = False
try:
    # Try to connect to Redis to check availability
    redis_client = redis.StrictRedis(
        host=REDIS_HOST, 
        port=int(REDIS_PORT), 
        db=0, 
        socket_connect_timeout=2,
        socket_timeout=2,
        decode_responses=False
    )
    redis_client.ping()
    REDIS_AVAILABLE = True
    print(f"Redis connection successful: {REDIS_HOST}:{REDIS_PORT}")
    redis_client.close()
except Exception as e:
    print(f"Redis not available at {REDIS_HOST}:{REDIS_PORT} - using in-memory channel layer. Error: {e}")
    REDIS_AVAILABLE = False

if REDIS_AVAILABLE:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                "hosts": [(REDIS_HOST, int(REDIS_PORT))],
                "capacity": 1500,
                "expiry": 10,
            },
        },
    }
    print("Channel layer configured to use Redis")
else:
    # Fallback to in-memory channel layer if Redis is not available
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }
    print("Using in-memory channel layer (Redis not available)")
