# Generated by Django 5.2 on 2025-05-17 10:15

import commonapp.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='inventorystatus',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='customer_info',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='location',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='managers',
        ),
        migrations.AddField(
            model_name='inventory',
            name='price',
            field=models.CharField(default=1, max_length=550),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='serial_number_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventory',
            name='service_number',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='service_tag',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='unit_price',
            field=models.CharField(default=1, max_length=550),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customer_ticket', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='payable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='representativeName',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='representativePhone',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('IN PROGRESS', 'IN PROGRESS'), ('PARTIALY CLOSED', 'PARTIALY CLOSED'), ('PENDING APPROVAL', 'PENDING APPROVAL'), ('CLOSED', 'CLOSED')], default='OPEN', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='aisle',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='bay',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='mac_address',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='name',
            field=models.CharField(max_length=550),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to=commonapp.models.inventory_qr_path),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='serial_number',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='shelf',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='upc',
            field=models.CharField(max_length=550, unique=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='wifi_details',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='commonapp.inventorycategory'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('INFO', 'INFO'), ('SUCCESS', 'SUCCESS'), ('WARNING', 'WARNING'), ('ERROR', 'ERROR')], default='INFO', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ISSUE', 'ISSUE'), ('FEATURE REQUEST', 'FEATURE REQUEST'), ('GENERAL INQUIRY', 'GENERAL INQUIRY')], default='OPEN', max_length=100)),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketItemUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.PositiveIntegerField(default=1, help_text='Quantity of this item actually used by the technician')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('inventory_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='commonapp.inventorystatus')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_usages', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_usages', to='commonapp.ticket')),
            ],
            options={
                'verbose_name': 'Ticket Item Usage',
                'verbose_name_plural': 'Ticket Item Usages',
                'ordering': ['-used_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Service Customer', 'Service Customer'), ('Technician', 'Technician')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_ticket_notes', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='commonapp.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendingCustomerLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('location', models.CharField(max_length=1000)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_locations', to=settings.AUTH_USER_MODEL)),
                ('vending_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vending_locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit_amount', models.CharField(max_length=1000)),
                ('reading_date', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings_taken', to=settings.AUTH_USER_MODEL)),
                ('vending_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='commonapp.vendingcustomerlocation')),
            ],
            options={
                'ordering': ['-reading_date'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.ForeignKey(limit_choices_to={'role__in': ['Warehouse Manager']}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_managers', to='commonapp.warehouse')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
