# Generated by Django 5.2 on 2025-05-17 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0002_inventorycategory_vendor_alter_attachment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='aisle',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='bay',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='shelf',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='inventorystatus',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_statuses', to='commonapp.warehouse'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='inventorystatus',
            unique_together={('inventory', 'warehouse', 'status')},
        ),
        migrations.CreateModel(
            name='InventoryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aisle', models.CharField(blank=True, max_length=550, null=True)),
                ('shelf', models.CharField(blank=True, max_length=550, null=True)),
                ('bay', models.CharField(blank=True, max_length=550, null=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='commonapp.inventory')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commonapp.warehouse')),
            ],
            options={
                'ordering': ['warehouse__name'],
                'unique_together': {('inventory', 'warehouse')},
            },
        ),
    ]
