# Generated by Django 5.2 on 2025-05-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0003_remove_inventory_aisle_remove_inventory_bay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorystatus',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('in_use', 'In Use'), ('in_repair', 'In Repair')], max_length=100),
        ),
    ]
