# Generated by Django 5.2 on 2025-05-17 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0004_alter_inventorystatus_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='mac_address',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='serial_number',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='service_number',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='service_tag',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='wifi_details',
        ),
    ]
