# Generated by Django 5.2 on 2025-05-17 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0005_remove_inventory_mac_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorystatus',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_statuses', to='commonapp.warehouse'),
        ),
    ]
