# Generated by Django 5.2 on 2025-05-24 13:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0006_alter_inventorystatus_warehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketitemusage',
            name='inventory_status',
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(default=uuid.uuid4, max_length=36, unique=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_use', 'In Use'), ('in_repair', 'In Repair')], default='available', max_length=20)),
                ('attributes', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='commonapp.inventory')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='commonapp.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('inventory', 'item_id')},
            },
        ),
        migrations.AddField(
            model_name='ticketitemusage',
            name='inventory_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='commonapp.inventoryitem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='tickets', to='commonapp.inventoryitem'),
        ),
        migrations.DeleteModel(
            name='InventoryStatus',
        ),
    ]
