# Generated by Django 5.2 on 2025-05-25 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0007_remove_ticketitemusage_inventory_status_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='item_id',
        ),
    ]
