# Generated by Django 5.2 on 2025-05-25 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0008_alter_inventoryitem_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='item_usages',
            field=models.JSONField(blank=True, default=dict, help_text="JSON field storing item IDs used in the ticket, e.g., {'1': true, '2': true}", null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='TicketItemUsage',
        ),
    ]
