# Generated by Django 5.2 on 2025-05-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0009_ticket_item_usages_alter_ticket_assigned_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('IN PROGRESS', 'IN PROGRESS'), ('PARTIALLY CLOSED', 'PARTIALLY CLOSED'), ('PENDING APPROVAL', 'PENDING APPROVAL'), ('CLOSED', 'CLOSED')], default='OPEN', max_length=100),
        ),
    ]
