# Generated by Django 5.2 on 2025-05-27 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0011_alter_vendingcustomerlocation_assigned_to'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(choices=[('VENDOR_TO_WAREHOUSE', 'Vendor to Warehouse'), ('WAREHOUSE_TO_WAREHOUSE', 'Warehouse to Warehouse'), ('WAREHOUSE_TO_CUSTOMER', 'Warehouse to Customer'), ('CUSTOMER_TO_WAREHOUSE', 'Customer to Warehouse')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_object_id', models.PositiveIntegerField()),
                ('destination_object_id', models.PositiveIntegerField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_transfers', to=settings.AUTH_USER_MODEL)),
                ('destination_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_transfers', to='contenttypes.contenttype')),
                ('items', models.ManyToManyField(blank=True, related_name='transfers', to='commonapp.inventoryitem')),
                ('source_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_transfers', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
