# Generated by Django 5.2 on 2025-05-28 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0012_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('in_use', 'In Use'), ('consumed', 'Consumed'), ('in_repair', 'In Repair')], default='available', max_length=20),
        ),
    ]
