# Generated by Django 5.2 on 2025-05-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0013_alter_inventoryitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
