# Generated by Django 5.2 on 2025-06-01 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0016_alter_repair_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Status of the reconciliation', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Admin who approved the reconciliation', limit_choices_to={'role': 'Admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reconciliations', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(help_text='Warehouse Manager who created the reconciliation', limit_choices_to={'role': 'Warehouse Manager'}, on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(help_text='Warehouse being reconciled', on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='commonapp.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField(default=list, help_text='List of items with UPC, name, expected_quantity, actual_quantity, discrepancy_type, attributes, and action')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reconciliation', models.OneToOneField(help_text='Associated reconciliation session', on_delete=django.db.models.deletion.CASCADE, related_name='report', to='commonapp.reconciliation')),
                ('warehouse', models.ForeignKey(help_text='Warehouse where reconciliation occurred', on_delete=django.db.models.deletion.CASCADE, to='commonapp.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
