# Generated by Django 5.2 on 2025-06-01 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0017_reconciliation_reconciliationreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconciliation',
            name='created_by',
            field=models.ForeignKey(help_text='Warehouse Manager who created the reconciliation', on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to=settings.AUTH_USER_MODEL),
        ),
    ]
