# Generated by Django 5.2 on 2025-06-02 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0018_alter_reconciliation_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='reference_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
