# Generated by Django 5.2 on 2025-06-04 07:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0019_transfer_reference_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('vin', models.CharField(help_text='Vehicle Identification Number', max_length=17, unique=True)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_use', 'In Use'), ('in_maintenance', 'In Maintenance')], default='available', max_length=20)),
                ('current_mileage', models.PositiveIntegerField(default=0, help_text='Current odometer reading in miles')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_time', models.DateTimeField(default=django.utils.timezone.now, help_text='Time when vehicle was picked up')),
                ('return_time', models.DateTimeField(blank=True, help_text='Time when vehicle was returned', null=True)),
                ('pickup_mileage', models.PositiveIntegerField(help_text='Odometer reading at pickup')),
                ('return_mileage', models.PositiveIntegerField(blank=True, help_text='Odometer reading at return', null=True)),
                ('pickup_notes', models.TextField(blank=True, help_text='Notes at pickup', null=True)),
                ('return_notes', models.TextField(blank=True, help_text='Notes at return', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who picked up/returned the vehicle', on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_usages', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(help_text='Vehicle being used', on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='commonapp.vehicle')),
            ],
            options={
                'ordering': ['-pickup_time'],
            },
        ),
    ]
