# Generated by Django 5.2 on 2025-06-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0020_vehicle_vehicleusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('in_use', 'In Use'), ('in_maintenance', 'In Maintenance'), ('retired', 'Retired')], default='available', max_length=20),
        ),
    ]
