# Generated by Django 5.2 on 2025-06-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0021_alter_vehicle_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='attachment_type',
            field=models.CharField(blank=True, help_text="e.g., 'pickup' or 'return' for VehicleUsage", max_length=20, null=True),
        ),
    ]
