# Generated by Django 5.2 on 2025-06-06 15:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0022_attachment_attachment_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, help_text='The time when the shift started.')),
                ('end_time', models.DateTimeField(blank=True, help_text='The time when the shift ended.', null=True)),
                ('duration', models.DurationField(blank=True, help_text='The total duration of the shift.', null=True)),
                ('user', models.ForeignKey(help_text='The user who this shift belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
    ]
