# Generated by Django 5.2 on 2025-06-11 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0025_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('repair', 'Repair'), ('scheduled', 'Scheduled Maintenance'), ('inspection', 'Inspection'), ('other', 'Other')], help_text='Type of maintenance performed', max_length=20)),
                ('description', models.TextField(help_text='Description of maintenance/repair work')),
                ('cost', models.DecimalField(decimal_places=2, help_text='Cost of maintenance/repair', max_digits=10)),
                ('service_provider', models.CharField(help_text='Name of service provider or mechanic', max_length=255)),
                ('start_date', models.DateTimeField(help_text='When maintenance/repair started')),
                ('end_date', models.DateTimeField(blank=True, help_text='When maintenance/repair was completed', null=True)),
                ('mileage_at_maintenance', models.PositiveIntegerField(help_text='Vehicle mileage when maintenance was performed')),
                ('next_maintenance_date', models.DateField(blank=True, help_text='Scheduled date for next maintenance', null=True)),
                ('next_maintenance_mileage', models.PositiveIntegerField(blank=True, help_text='Mileage at which next maintenance is recommended', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(help_text='Vehicle being maintained', on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='commonapp.vehicle')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
