# Generated by Django 5.2 on 2025-06-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0026_vehiclemaintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='defective_items',
            field=models.JSONField(blank=True, default=dict, help_text="JSON field storing defective item IDs, e.g., {'1': true, '2': true}", null=True),
        ),
    ]
