# Generated by Django 5.2 on 2025-06-21 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0027_ticket_defective_items'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashDrawer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='closed', help_text='Current status of the cash drawer', max_length=10)),
                ('opening_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount when cash drawer was opened', max_digits=10)),
                ('current_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Current amount in cash drawer', max_digits=10)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(help_text='User who opened the cash drawer', on_delete=django.db.models.deletion.CASCADE, related_name='cash_drawers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='CashEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('opening', 'Opening'), ('sale', 'Sale'), ('refund', 'Refund'), ('adjustment', 'Adjustment'), ('closing', 'Closing')], help_text='Type of cash entry', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount of the entry', max_digits=10)),
                ('description', models.CharField(help_text='Description of the entry', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cash_drawer', models.ForeignKey(help_text='Associated cash drawer', on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='commonapp.cashdrawer')),
                ('created_by', models.ForeignKey(help_text='User who created this entry', on_delete=django.db.models.deletion.CASCADE, related_name='cash_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cash Entry',
                'verbose_name_plural': 'Cash Entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
