# Generated by Django 5.2 on 2025-06-21 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0028_cashdrawer_cashentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount in the vault', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vault',
                'verbose_name_plural': 'Vaults',
            },
        ),
        migrations.AlterField(
            model_name='cashdrawer',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', help_text='Current status of the cash drawer', max_length=10),
        ),
        migrations.CreateModel(
            name='VaultEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], help_text='Type of vault entry', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount of the entry', max_digits=10)),
                ('description', models.CharField(help_text='Description of the entry', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(help_text='User who created this entry', on_delete=django.db.models.deletion.CASCADE, related_name='vault_entries', to=settings.AUTH_USER_MODEL)),
                ('vault', models.ForeignKey(help_text='Associated vault', on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='commonapp.vault')),
            ],
            options={
                'verbose_name': 'Vault Entry',
                'verbose_name_plural': 'Vault Entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
