# Generated by Django 5.2 on 2025-06-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0029_vault_alter_cashdrawer_status_vaultentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaultentry',
            name='entry_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer')], help_text='Type of vault entry', max_length=20),
        ),
    ]
