# Generated by Django 5.2 on 2025-06-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0030_alter_vaultentry_entry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaultentry',
            name='description',
            field=models.CharField(help_text='Description of the entry'),
        ),
    ]
