# Generated by Django 5.2 on 2025-06-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0031_alter_vaultentry_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashentry',
            name='amount',
            field=models.DecimalField(decimal_places=20, help_text='Amount of the entry', max_digits=100),
        ),
    ]
