# Generated by Django 5.2 on 2025-06-21 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0032_alter_cashentry_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceChargeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the charge type (e.g., Service Charge, Tax)', max_length=255)),
                ('charge_type', models.CharField(choices=[('FIXED', 'Fixed Amount'), ('PERCENTAGE', 'Percentage')], help_text='Whether this is a fixed amount or percentage', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, help_text='Fixed amount or percentage value', max_digits=10)),
                ('is_compulsory', models.BooleanField(default=False, help_text='Whether this charge is automatically applied to all invoices')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this charge type is currently active')),
                ('description', models.TextField(blank=True, help_text='Description of when and why this charge is applied', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Invoice Charge Type',
                'verbose_name_plural': 'Invoice Charge Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(help_text='Unique invoice number', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='DRAFT', help_text='Current status of the invoice', max_length=20)),
                ('issue_date', models.DateField(auto_now_add=True, help_text='Date when invoice was issued')),
                ('due_date', models.DateField(blank=True, help_text='Due date for payment', null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, help_text='Subtotal before charges and taxes', max_digits=12)),
                ('total_charges', models.DecimalField(decimal_places=2, default=0.0, help_text='Total of all additional charges', max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount including all charges', max_digits=12)),
                ('notes', models.TextField(blank=True, help_text='Additional notes for the invoice', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created the invoice', on_delete=django.db.models.deletion.CASCADE, related_name='created_invoices', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='Customer for whom the invoice is created', on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
                ('transfer', models.ForeignKey(blank=True, help_text='Associated transfer (if created from transfer)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='commonapp.transfer')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount of the charge', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(help_text='Associated invoice', on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='commonapp.invoice')),
                ('charge_type', models.ForeignKey(help_text='Type of charge being applied', on_delete=django.db.models.deletion.CASCADE, related_name='invoice_charges', to='commonapp.invoicechargetype')),
            ],
            options={
                'verbose_name': 'Invoice Charge',
                'verbose_name_plural': 'Invoice Charges',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity of the item')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Unit price of the item', max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total price for this item (quantity * unit_price)', max_digits=10)),
                ('description', models.CharField(blank=True, help_text='Additional description for this item', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory_item', models.ForeignKey(help_text='Associated inventory item', on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='commonapp.inventoryitem')),
                ('invoice', models.ForeignKey(help_text='Associated invoice', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='commonapp.invoice')),
            ],
            options={
                'verbose_name': 'Invoice Item',
                'verbose_name_plural': 'Invoice Items',
                'ordering': ['created_at'],
            },
        ),
    ]
