# Generated by Django 5.2 on 2025-06-22 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0033_invoicechargetype_invoice_invoicecharge_invoiceitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashentry',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this entry', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
