# Generated by Django 5.2 on 2025-06-22 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0034_alter_cashentry_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashdrawer',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who opened the cash drawer', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_drawers', to=settings.AUTH_USER_MODEL),
        ),
    ]
