# Generated by Django 5.2 on 2025-06-22 18:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0035_alter_cashdrawer_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the permission was assigned')),
                ('assigned_by', models.ForeignKey(blank=True, help_text='User who assigned this permission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_location_permissions', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(help_text='Location the user is assigned to', on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='commonapp.vendingcustomerlocation')),
                ('user', models.ForeignKey(help_text='User who is assigned to the location', on_delete=django.db.models.deletion.CASCADE, related_name='location_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Location Permission',
                'verbose_name_plural': 'Location Permissions',
                'ordering': ['-assigned_at'],
                'unique_together': {('user', 'location')},
            },
        ),
    ]
