# Generated by Django 5.2 on 2025-06-28 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0036_locationpermission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerCustomerLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the link was created')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this link is currently active')),
                ('created_by', models.ForeignKey(help_text='User who created this link', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_partner_links', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(help_text='Partner user who is linked to the vending customer', limit_choices_to={'role': 'Partner'}, on_delete=django.db.models.deletion.CASCADE, related_name='customer_links', to=settings.AUTH_USER_MODEL)),
                ('vending_customer', models.ForeignKey(help_text='Vending customer who is linked to the partner', limit_choices_to={'role': 'Vending Customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='partner_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partner Customer Link',
                'verbose_name_plural': 'Partner Customer Links',
                'ordering': ['-created_at'],
                'unique_together': {('partner', 'vending_customer')},
            },
        ),
    ]
