# Generated by Django 5.2 on 2025-07-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0037_partnercustomerlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashentry',
            name='entry_type',
            field=models.CharField(choices=[('opening', 'Opening'), ('sale', 'Sale'), ('refund', 'Refund'), ('adjustment', 'Adjustment'), ('withdrawal', 'Withdrawal'), ('closing', 'Closing')], help_text='Type of cash entry', max_length=20),
        ),
    ]
