# Generated by Django 5.2 on 2025-07-05 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0039_add_secondary_vehicles_to_vehicle_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleusage',
            name='is_secondary_usage',
            field=models.BooleanField(default=False, help_text='Whether this usage is for a secondary vehicle'),
        ),
        migrations.AddField(
            model_name='vehicleusage',
            name='primary_usage',
            field=models.ForeignKey(blank=True, help_text='Reference to the primary vehicle usage if this is a secondary vehicle usage', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_vehicle_usages', to='commonapp.vehicleusage'),
        ),
    ]
