# Generated by Django 5.2 on 2025-07-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0040_vehicleusage_is_secondary_usage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='current_mileage',
            field=models.PositiveBigIntegerField(default=0, help_text='Current odometer reading in miles'),
        ),
        migrations.AlterField(
            model_name='vehicleusage',
            name='pickup_mileage',
            field=models.PositiveBigIntegerField(help_text='Odometer reading at pickup'),
        ),
        migrations.AlterField(
            model_name='vehicleusage',
            name='return_mileage',
            field=models.PositiveBigIntegerField(blank=True, help_text='Odometer reading at return', null=True),
        ),
    ]
