# Generated by Django 5.2 on 2025-07-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0041_alter_vehicle_current_mileage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vault',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount in the vault', max_digits=21),
        ),
    ]
