# Generated by Django 5.2 on 2025-07-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0042_alter_vault_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicechargetype',
            name='value',
            field=models.DecimalField(decimal_places=2, help_text='Fixed amount or percentage value', max_digits=21),
        ),
        migrations.AlterField(
            model_name='vaultentry',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount of the entry', max_digits=21),
        ),
    ]
