# Generated by Django 5.2 on 2025-07-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0043_alter_invoicechargetype_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Subtotal before charges and taxes', max_digits=21),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount including all charges', max_digits=21),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_charges',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total of all additional charges', max_digits=21),
        ),
    ]
