# Generated by Django 5.1.6 on 2025-07-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0044_alter_invoice_subtotal_alter_invoice_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaultentry',
            name='description',
            field=models.CharField(help_text='Description of the entry', max_length=255),
        ),
    ]
