# Generated by Django 5.1.6 on 2025-07-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0045_alter_vaultentry_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='charges',
            field=models.JSONField(blank=True, default=list, help_text="JSON field storing ticket charges, e.g., [{'amount': 100.00, 'description': 'Service fee'}]", null=True),
        ),
    ]
