# Generated by Django 5.1.6 on 2025-07-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0046_ticket_charges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicechargetype',
            name='charge_type',
            field=models.CharField(choices=[('FIXED', 'Fixed Amount'), ('PERCENTAGE', 'Percentage'), ('MANUAL', 'Manual')], help_text='Whether this is a fixed amount or percentage', max_length=20),
        ),
    ]
