# Generated by Django 5.2 on 2025-07-14 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0047_alter_invoicechargetype_charge_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the price matrix (e.g., Standard Tax Matrix)', max_length=255)),
                ('min_amount', models.DecimalField(decimal_places=2, help_text='Minimum amount for this tax bracket', max_digits=10)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum amount for this tax bracket (null for unlimited)', max_digits=10, null=True)),
                ('tax_percentage', models.DecimalField(decimal_places=2, help_text='Tax percentage to apply (e.g., 10.00 for 10%)', max_digits=5)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this price matrix rule is currently active')),
                ('description', models.TextField(blank=True, help_text='Description of when this tax bracket applies', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Price Matrix',
                'verbose_name_plural': 'Price Matrices',
                'ordering': ['min_amount'],
                'unique_together': {('min_amount', 'max_amount')},
            },
        ),
    ]
