# Generated by Django 5.2 on 2025-07-18 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0048_pricematrix'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashentry',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Customer associated with this entry (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cashentry',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this entry', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_entries_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
