# Generated by Django 5.2 on 2025-07-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0049_cashentry_customer_alter_cashentry_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemaintenance',
            name='cost',
            field=models.DecimalField(decimal_places=2, help_text='Cost of maintenance/repair', max_digits=1000),
        ),
    ]
