# Generated by Django 5.2.3 on 2025-08-04 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0050_alter_vehiclemaintenance_cost'),
        ('custom_user', '0005_rename_customer_profile_to_store_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashentry',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='customer',
        ),
        migrations.AddField(
            model_name='cashentry',
            name='store',
            field=models.ForeignKey(blank=True, help_text='Store associated with this entry (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_cash_entries', to='custom_user.storeprofile'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='store',
            field=models.ForeignKey(blank=True, help_text='Store that owns this item (when status is consumed)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_inventory_items', to='custom_user.storeprofile'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='store',
            field=models.ForeignKey(blank=True, help_text='Store for which the invoice is created', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_invoices', to='custom_user.storeprofile'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='store',
            field=models.ForeignKey(blank=True, help_text='Store for which this ticket is created', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_tickets', to='custom_user.storeprofile'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='transfer_type',
            field=models.CharField(choices=[('VENDOR_TO_WAREHOUSE', 'Vendor to Warehouse'), ('WAREHOUSE_TO_WAREHOUSE', 'Warehouse to Warehouse'), ('WAREHOUSE_TO_STORE', 'Warehouse to Store'), ('STORE_TO_WAREHOUSE', 'Store to Warehouse')], max_length=50),
        ),
    ]
