# Generated by Django 5.2.4 on 2025-08-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0051_update_models_to_use_store_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='transfer_type',
            field=models.CharField(choices=[('VENDOR_TO_WAREHOUSE', 'Vendor to Warehouse'), ('WAREHOUSE_TO_WAREHOUSE', 'Warehouse to Warehouse'), ('WAREHOUSE_TO_STORE', 'Warehouse to Store'), ('STORE_TO_WAREHOUSE', 'Store to Warehouse'), ('WAREHOUSE_TO_CUSTOMER', 'Warehouse to Customer'), ('CUSTOMER_TO_WAREHOUSE', 'Customer to Warehouse')], max_length=50),
        ),
    ]
