# Generated by Django 5.2.4 on 2025-08-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0052_notification_link_alter_transfer_transfer_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name'], 'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='inventorycategory',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='supportticket',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='vendingcustomerlocation',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='vendor',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
