# Generated by Django 4.2.23 on 2025-08-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0053_alter_group_options_alter_inventory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_emails', models.TextField(blank=True, default='', help_text='Comma-separated list of tracking/notification recipient emails')),
                ('maintenance_emails', models.TextField(blank=True, default='', help_text='Comma-separated list of vehicle maintenance notification emails')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Configuration',
                'verbose_name_plural': 'Platform Configuration',
            },
        ),
    ]
