# Generated by Django 4.2.23 on 2025-08-30 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0054_platformconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformconfig',
            name='maintenance_emails',
            field=models.JSONField(blank=True, default=list, help_text='List of vehicle maintenance notification emails'),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='tracking_emails',
            field=models.JSONField(blank=True, default=list, help_text='List of tracking/notification recipient emails'),
        ),
    ]
