# Generated by Django 4.2.23 on 2025-09-01 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0055_alter_platformconfig_maintenance_emails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfig',
            name='default_from_email',
            field=models.EmailField(blank=True, help_text='Default sender email address', max_length=254),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='email_host',
            field=models.CharField(blank=True, help_text='SMTP server hostname (e.g., smtp.gmail.com, smtp.ovh.com, smtp.godaddy.com)', max_length=255),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='email_host_password',
            field=models.CharField(blank=True, help_text='SMTP password or app password', max_length=255),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='email_host_user',
            field=models.EmailField(blank=True, help_text='SMTP username/email address', max_length=254),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='email_port',
            field=models.IntegerField(default=587, help_text='SMTP server port number (587 for TLS, 465 for SSL, 25 for non-TLS)'),
        ),
    ]
