# Generated by Django 4.2.23 on 2025-09-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0056_platformconfig_default_from_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='slider_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
