# Generated by Django 4.2.23 on 2025-09-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0057_sliderslide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformconfig',
            name='default_from_email',
            field=models.EmailField(blank=True, help_text='Default sender email address (can be alias like contact@ttincnc.com)', max_length=254),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='email_host_user',
            field=models.EmailField(blank=True, help_text='SMTP login username/email address (e.g., user@ttincnc.com for Google Workspace)', max_length=254),
        ),
    ]
