# Generated by Django 4.2.23 on 2025-09-21 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0058_alter_platformconfig_default_from_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashentry',
            name='invoice',
            field=models.ForeignKey(blank=True, help_text='Associated invoice (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_entries', to='commonapp.invoice'),
        ),
        migrations.AlterField(
            model_name='cashentry',
            name='entry_type',
            field=models.CharField(choices=[('opening', 'Opening'), ('sale', 'Sale'), ('fill', 'Fill'), ('refund', 'Refund'), ('adjustment', 'Adjustment'), ('withdrawal', 'Withdrawal'), ('bleed', 'Bleed'), ('closing', 'Closing')], help_text='Type of cash entry', max_length=20),
        ),
    ]
