# Generated by Django 4.2.23 on 2025-10-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0059_cashentry_invoice_alter_cashentry_entry_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferredSoftwareOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.JSONField(blank=True, default=list, help_text='List of preferred software option labels')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Preferred Software Options',
                'verbose_name_plural': 'Preferred Software Options',
            },
        ),
    ]
