# Generated by Django 5.2 on 2025-10-26 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0060_preferredsoftwareoptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaultentry',
            name='vault_amount_at_time',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount in vault at the time this vault entry was created', max_digits=21, null=True),
        ),
    ]
