# Generated by Django 5.2 on 2025-10-26 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0061_vaultentry_vault_amount_at_time'),
        ('custom_user', '0011_add_is_active_to_store_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnercustomerlink',
            name='store',
            field=models.ForeignKey(blank=True, null=True, help_text='Store associated with this link', on_delete=django.db.models.deletion.CASCADE, related_name='partner_customer_links', to='custom_user.storeprofile'),
        ),
    ]
