# Generated by Django 5.2 on 2025-06-29 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commonapp', '0037_partnercustomerlink'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblyTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('IN PROGRESS', 'IN PROGRESS'), ('PARTIALLY CLOSED', 'PARTIALLY CLOSED'), ('PENDING APPROVAL', 'PENDING APPROVAL'), ('CLOSED', 'CLOSED')], default='OPEN', max_length=100)),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('deadline', models.DateField(blank=True, null=True)),
                ('item_usages', models.JSONField(blank=True, default=dict, help_text="JSON field storing item IDs used in the assembly ticket, e.g., {'1': true, '2': true}", null=True)),
                ('defective_items', models.JSONField(blank=True, default=dict, help_text="JSON field storing defective item IDs, e.g., {'1': true, '2': true}", null=True)),
                ('assembled_item_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('assembled_item_attributes', models.JSONField(blank=True, default=dict, help_text='Attributes for the assembled item (serial_number, mac_address, etc.)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('flagged', models.BooleanField(default=False)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assembly_ticket_assigned', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ManyToManyField(related_name='assigned_assembly_tickets', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_assembly_tickets', to=settings.AUTH_USER_MODEL)),
                ('items', models.ManyToManyField(blank=True, related_name='assembly_tickets', to='commonapp.inventoryitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssemblyNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Technician', 'Technician'), ('Manager', 'Manager')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_assembly_notes', to=settings.AUTH_USER_MODEL)),
                ('assembly_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='assembly.assemblyticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
