# Generated by Django 5.2 on 2025-06-29 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0001_initial'),
        ('commonapp', '0037_partnercustomerlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='assemblyticket',
            name='assembled_item_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assembly_tickets', to='commonapp.inventorycategory'),
        ),
        migrations.AddField(
            model_name='assemblyticket',
            name='assembled_item_serial_number_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assemblyticket',
            name='assembled_item_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='assemblyticket',
            name='assembled_item_upc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
