# Generated by Django 5.2 on 2025-06-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0002_assemblyticket_assembled_item_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assemblyticket',
            name='assembly_notes',
            field=models.TextField(blank=True, help_text='Main assembly notes for the ticket', null=True),
        ),
    ] 