# Generated by Django 5.2 on 2025-07-15 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0003_assemblyticket_assembly_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='assemblyticket',
            name='assembled_items',
            field=models.JSONField(blank=True, default=list, help_text='List of assembled item dicts for this ticket (name, upc, category, unit_price, serial_number_required, quantity, attributes_list)', null=True),
        ),
    ]
