# Generated by Django 5.2.4 on 2025-08-20 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0004_assemblyticket_assembled_items'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assemblyticket',
            options={'ordering': ['title']},
        ),
    ]
