# Generated by Django 5.2 on 2025-05-17 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=130)),
                ('email', models.EmailField(max_length=130, unique=True, verbose_name='email')),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('Technician', 'Technician'), ('Warehouse Manager', 'Warehouse Manager'), ('Warehouse Technician', 'Warehouse Technician'), ('Vending Customer', 'Vending Customer'), ('Service Customer', 'Service Customer'), ('Reporter', 'Reporter'), ('External User', 'External User'), ('Deactivated', 'Deactivated')], max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True)),
                ('pay_rate', models.CharField(blank=True, max_length=300, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('check_in_required', models.BooleanField(default=False)),
                ('is_broker', models.BooleanField(default=False)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
            ],
            options={
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('action', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=255)),
                ('status_code', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(blank=True, max_length=555, null=True)),
                ('store_address', models.CharField(blank=True, max_length=500, null=True)),
                ('store_city', models.CharField(blank=True, max_length=555, null=True)),
                ('store_zip_code', models.CharField(blank=True, max_length=550, null=True)),
                ('store_billing_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('store_phone', models.CharField(blank=True, max_length=550, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=555, null=True)),
                ('owner_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('owner_phone', models.CharField(blank=True, max_length=550, null=True)),
                ('distributor_name', models.CharField(blank=True, max_length=555, null=True)),
                ('distributor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('distributor_phone', models.CharField(blank=True, max_length=550, null=True)),
                ('manager_name', models.CharField(blank=True, max_length=555, null=True)),
                ('manager_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('manager_phone', models.CharField(blank=True, max_length=550, null=True)),
                ('open', models.TimeField(blank=True, null=True)),
                ('close', models.TimeField(blank=True, null=True)),
                ('preferred_software', models.JSONField(default=dict)),
                ('lisence', models.FileField(blank=True, null=True, upload_to='lisence_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
