# Generated by Django 5.2 on 2025-06-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0002_userpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('Technician', 'Technician'), ('Warehouse Manager', 'Warehouse Manager'), ('Warehouse Technician', 'Warehouse Technician'), ('Vending Customer', 'Vending Customer'), ('Service Customer', 'Service Customer'), ('Reporter', 'Reporter'), ('External User', 'External User'), ('Deactivated', 'Deactivated'), ('Partner', 'Partner')], max_length=50),
        ),
    ]
