# Generated by Django 5.1.6 on 2025-07-12 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0003_alter_account_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Display name for the favorite', max_length=255)),
                ('url', models.CharField(help_text='URL path of the favorite page', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this favorite was created')),
                ('user', models.ForeignKey(help_text='User who created this favorite', on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Favorite',
                'verbose_name_plural': 'User Favorites',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'url')},
            },
        ),
    ]
