# Generated by Django 5.2.3 on 2025-08-04 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0004_userfavorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(blank=True, max_length=555, null=True)),
                ('store_address', models.CharField(blank=True, max_length=500, null=True)),
                ('store_city', models.CharField(blank=True, max_length=555, null=True)),
                ('store_zip_code', models.CharField(blank=True, max_length=550, null=True)),
                ('store_billing_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('store_phone', models.CharField(blank=True, max_length=550, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=555, null=True)),
                ('owner_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('owner_phone', models.CharField(blank=True, max_length=550, null=True)),
                ('distributor_name', models.CharField(blank=True, max_length=555, null=True)),
                ('distributor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('distributor_phone', models.CharField(blank=True, max_length=550, null=True)),
                ('manager_name', models.CharField(blank=True, max_length=555, null=True)),
                ('manager_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('manager_phone', models.CharField(blank=True, max_length=550, null=True)),
                ('open', models.TimeField(blank=True, null=True)),
                ('close', models.TimeField(blank=True, null=True)),
                ('preferred_software', models.JSONField(default=dict)),
                ('lisence', models.FileField(blank=True, null=True, upload_to='lisence_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Store Profile',
                'verbose_name_plural': 'Store Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='CustomerProfile',
        ),
    ]
