# Generated by Django 5.2.3 on 2025-08-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0005_rename_customer_profile_to_store_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeprofile',
            name='lisence',
        ),
        migrations.AddField(
            model_name='account',
            name='license',
            field=models.FileField(blank=True, null=True, upload_to='license_images/'),
        ),
    ]
