# Generated by Django 5.2.4 on 2025-08-20 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0006_remove_storeprofile_lisence_account_license'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['username']},
        ),
    ]
