# Generated by Django 5.2 on 2025-09-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0007_alter_account_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='first_login_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
