# Generated by Django 5.2 on 2025-10-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0008_account_first_login_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='permissions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
