# Generated by Django 4.2.23 on 2025-10-18 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0009_account_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('Technician', 'Technician'), ('Warehouse Manager', 'Warehouse Manager'), ('Warehouse Technician', 'Warehouse Technician'), ('Vending Customer', 'Vending Customer'), ('Service Customer', 'Service Customer'), ('Reporter', 'Reporter'), ('External User', 'External User'), ('Deactivated', 'Deactivated'), ('Partner', 'Partner'), ('Employee', 'Employee')], max_length=50),
        ),
    ]
