# Generated by Django 4.2.23 on 2025-10-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0010_alter_account_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeprofile',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the store is active or deactivated'),
        ),
    ]
